# Generated by Django 4.0.2 on 2022-03-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board', models.CharField(blank=True, max_length=10, null=True)),
                ('board_title', models.CharField(blank=True, max_length=50, null=True)),
                ('board_content', models.TextField(blank=True, null=True)),
                ('board_num', models.IntegerField(blank=True, null=True)),
                ('board_place', models.CharField(blank=True, max_length=20, null=True)),
                ('board_recruitdate', models.DateField(blank=True, null=True)),
                ('board_time', models.DateField(blank=True, null=True)),
                ('board_on_off', models.CharField(blank=True, max_length=20, null=True)),
                ('board_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('board_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clipping',
            fields=[
                ('clip_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'clipping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('comment_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('revi_id', models.AutoField(primary_key=True, serialize=False)),
                ('revi_title', models.CharField(blank=True, max_length=50, null=True)),
                ('revi_content', models.TextField(blank=True, null=True)),
                ('revi_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'revision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=10, null=True)),
                ('user_pwd', models.CharField(blank=True, max_length=10, null=True)),
                ('user_email', models.CharField(blank=True, max_length=20, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('favcom1', models.CharField(blank=True, max_length=20, null=True)),
                ('favcom2', models.CharField(blank=True, max_length=20, null=True)),
                ('favlang1', models.CharField(blank=True, max_length=20, null=True)),
                ('favlang2', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('wiki_id', models.AutoField(primary_key=True, serialize=False)),
                ('wiki_title', models.CharField(blank=True, max_length=50, null=True)),
                ('wiki_kind', models.CharField(blank=True, max_length=20, null=True)),
                ('wiki_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wiki',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
