# Generated by Django 4.0.2 on 2022-03-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_clipping_comment_revision_user_wiki_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clipping',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='revision',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wiki',
            options={},
        ),
    ]
