# Generated by Django 4.0.2 on 2022-03-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_options_alter_clipping_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clipping',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='revision',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='wiki',
            options={'managed': False},
        ),
    ]
